// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SkyNet.Data;

#nullable disable

namespace SkyNet.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251007152422_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("SkyNet.Models.ArchivoSolicitud", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<long>("Fk_Solicitud")
                        .HasColumnType("bigint");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.HasKey("Id");

                    b.HasIndex("Fk_Solicitud");

                    b.ToTable("ArchivoSolicitud");
                });

            modelBuilder.Entity("SkyNet.Models.Cliente", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("SkyNet.Models.DTOs.SolicitudAsignacionDetalleDto", b =>
                {
                    b.Property<DateTime?>("AsignacionCreadaUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("AsignacionFechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("AsignacionFechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<long>("AsignacionId")
                        .HasColumnType("bigint");

                    b.Property<string>("AsignacionNotas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<int>("EstadoAsignacion")
                        .HasColumnType("int");

                    b.Property<int>("EstadoSolicitud")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Fecha_Fin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Fecha_Inicio")
                        .HasColumnType("datetime2");

                    b.Property<long>("FkTecnico")
                        .HasColumnType("bigint");

                    b.Property<string>("GrupoEtiqueta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("IdGrupo")
                        .HasColumnType("bigint");

                    b.Property<long>("IdSolicitud")
                        .HasColumnType("bigint");

                    b.Property<double?>("Latitud")
                        .HasColumnType("float");

                    b.Property<double?>("Longitud")
                        .HasColumnType("float");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prioridad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SupervisorNombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TecnicoNombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ticket")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable((string)null);

                    b.ToView(null, (string)null);
                });

            modelBuilder.Entity("SkyNet.Models.DTOs.SolicitudAsignacionListado", b =>
                {
                    b.Property<byte>("Estado")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("FechaAsignacionUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Fecha_Fin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Fecha_Inicio")
                        .HasColumnType("datetime2");

                    b.Property<long>("FkTecnico")
                        .HasColumnType("bigint");

                    b.Property<string>("GrupoEtiqueta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<int>("IdGrupo")
                        .HasColumnType("int");

                    b.Property<long>("IdSolicitud")
                        .HasColumnType("bigint");

                    b.Property<string>("Notas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SupervisorNombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TecnicoNombre")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable((string)null);

                    b.ToView(null, (string)null);
                });

            modelBuilder.Entity("SkyNet.Models.DTOs.SolicitudResumenDto", b =>
                {
                    b.Property<string>("Asignaciones_Json")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ASIGNACIONES_JSON");

                    b.Property<byte>("Estado_Agregado")
                        .HasColumnType("tinyint")
                        .HasColumnName("ESTADO_AGREGADO");

                    b.Property<DateTime?>("FechaVisita_Min")
                        .HasColumnType("datetime2")
                        .HasColumnName("FECHAVISITA_MIN");

                    b.Property<long>("IdSolicitud")
                        .HasColumnType("bigint")
                        .HasColumnName("IDSOLICITUD");

                    b.Property<string>("Supervisores")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SUPERVISORES");

                    b.Property<string>("Tecnicos")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TECNICOS");

                    b.ToTable((string)null);

                    b.ToView(null, (string)null);
                });

            modelBuilder.Entity("SkyNet.Models.DTOs.SolicitudTrackingTimelineRow", b =>
                {
                    b.Property<byte>("Estado")
                        .HasColumnType("tinyint");

                    b.Property<string>("EstadoTexto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaUtc")
                        .HasColumnType("datetime2");

                    b.Property<long>("SolicitudId")
                        .HasColumnType("bigint");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("SolicitudTrackingTimeline");
                });

            modelBuilder.Entity("SkyNet.Models.Empleado", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id_Empleado");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Apellidos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cargo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DPI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<string>("Nombres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("UserId");

                    b.HasKey("Id")
                        .HasName("Id_Empleado");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("IX_Empleado_UserId_Unico")
                        .HasFilter("[UserId] IS NOT NULL");

                    b.ToTable("Empleado", (string)null);
                });

            modelBuilder.Entity("SkyNet.Models.GrupoSupervisorTec", b =>
                {
                    b.Property<int>("IdGrupo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdGrupo");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdGrupo"));

                    b.Property<bool>("Estado")
                        .HasColumnType("bit")
                        .HasColumnName("Estado");

                    b.Property<DateTime>("FechaCreacionUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaCreacionUtc");

                    b.Property<long>("FkSupervisor")
                        .HasColumnType("bigint")
                        .HasColumnName("FkSupervisor");

                    b.Property<long>("FkTecnico")
                        .HasColumnType("bigint")
                        .HasColumnName("FkTecnico");

                    b.HasKey("IdGrupo")
                        .HasName("Id_Grupo_Supervisor_Tec");

                    b.HasIndex("FkSupervisor");

                    b.HasIndex("FkTecnico");

                    b.ToTable("Grupo_Supervisor_Tec", (string)null);
                });

            modelBuilder.Entity("SkyNet.Models.Solicitud", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id_Solicitud");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("nvarchar(1500)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<double?>("Latitud")
                        .HasColumnType("float");

                    b.Property<double?>("Longitud")
                        .HasColumnType("float");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Prioridad")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Ticket")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id")
                        .HasName("Id_Solicitud");

                    b.ToTable("Solicitud", (string)null);
                });

            modelBuilder.Entity("SkyNet.Models.SolicitudAsignacion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id_Solicitud_Asignacion");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<byte>("Estado")
                        .HasColumnType("tinyint")
                        .HasColumnName("Estado");

                    b.Property<DateTime>("FechaAsignacionUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaAsignacionUtc");

                    b.Property<DateTime?>("Fecha_Fin")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaFin");

                    b.Property<DateTime?>("Fecha_Inicio")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaInicio");

                    b.Property<long>("FkSolicitud")
                        .HasColumnType("bigint")
                        .HasColumnName("FkSolicitud");

                    b.Property<long>("FkTecnico")
                        .HasColumnType("bigint")
                        .HasColumnName("FkTecnico");

                    b.Property<int>("IdGrupo")
                        .HasColumnType("int")
                        .HasColumnName("IdGrupo");

                    b.Property<string>("Notas")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Notas");

                    b.HasKey("Id")
                        .HasName("Id_Solicitud_Asignacion");

                    b.HasIndex("FkSolicitud", "FkTecnico", "Estado")
                        .IsUnique()
                        .HasDatabaseName("UX_Solicitud_Asignacion_ActivaPorTec")
                        .HasFilter("[Estado] = 1");

                    b.ToTable("Solicitud_Asignacion", (string)null);
                });

            modelBuilder.Entity("SolicitudTracking", b =>
                {
                    b.Property<long>("IdTracking")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("IdTracking");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdTracking"));

                    b.Property<byte?>("Estado")
                        .HasColumnType("tinyint")
                        .HasColumnName("Estado");

                    b.Property<DateTime>("FechaUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("FechaUtc")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<long>("FkSolicitud")
                        .HasColumnType("bigint")
                        .HasColumnName("FkSolicitud");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("UserId");

                    b.HasKey("IdTracking")
                        .HasName("PK_Solicitud_Tracking");

                    b.HasIndex("FkSolicitud");

                    b.ToTable("Solicitud_Tracking", "dbo");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SkyNet.Models.ArchivoSolicitud", b =>
                {
                    b.HasOne("SkyNet.Models.Solicitud", "Solicitud")
                        .WithMany("Archivos")
                        .HasForeignKey("Fk_Solicitud")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Solicitud");
                });

            modelBuilder.Entity("SkyNet.Models.Empleado", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Empleado_AspNetUsers_UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SkyNet.Models.GrupoSupervisorTec", b =>
                {
                    b.HasOne("SkyNet.Models.Empleado", "Supervisor")
                        .WithMany()
                        .HasForeignKey("FkSupervisor")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_GrupoSupervisor_Supervisor");

                    b.HasOne("SkyNet.Models.Empleado", "Tecnico")
                        .WithMany()
                        .HasForeignKey("FkTecnico")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_GrupoSupervisor_Tecnico");

                    b.Navigation("Supervisor");

                    b.Navigation("Tecnico");
                });

            modelBuilder.Entity("SolicitudTracking", b =>
                {
                    b.HasOne("SkyNet.Models.Solicitud", "Solicitud")
                        .WithMany()
                        .HasForeignKey("FkSolicitud")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_SolicitudTracking_Solicitud");

                    b.Navigation("Solicitud");
                });

            modelBuilder.Entity("SkyNet.Models.Solicitud", b =>
                {
                    b.Navigation("Archivos");
                });
#pragma warning restore 612, 618
        }
    }
}
